parameters:
    ezpublish.fieldType.ngclasslist.class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Type
    ezpublish.fieldType.indexable.ngclasslist.class: eZ\Publish\Core\FieldType\Unindexed

services:
    ezpublish.fieldType.ngclasslist:
        class: %ezpublish.fieldType.ngclasslist.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ngclasslist}

    ezpublish.fieldType.indexable.ngclasslist:
        class: %ezpublish.fieldType.indexable.ngclasslist.class%
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ngclasslist}
