parameters:
    ezpublish.fieldType.ngclasslist.class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Type

services:
    ezpublish.fieldType.ngclasslist:
        class: %ezpublish.fieldType.ngclasslist.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ngclasslist}
