services:
    netgen_class_list.field_type:
        class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Type
        public: true
        parent: ezpublish.fieldType
        tags:
            - { name: ezplatform.field_type, alias: ngclasslist }

    netgen_class_list.field_type.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        public: false
        tags:
            - { name: ezplatform.field_type.indexable, alias: ngclasslist }
