services:
    netgen_class_list.field_type:
        class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Type
        public: true
        parent: ezpublish.fieldType
        tags:
            - { name: ezpublish.fieldType, alias: ngclasslist }

    netgen_class_list.field_type.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        public: false
        tags:
            - { name: ezpublish.fieldType.indexable, alias: ngclasslist }

    Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Mapper\FormMapper:
        autowire: true
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ngclasslist }
            - { name: ez.fieldFormMapper.value, fieldType: ngclasslist }
