services:
    netgen_class_list.field_type.legacy.converter:
        class: Netgen\Bundle\ContentTypeListBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\ContentTypeListConverter
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: ngclasslist }
